### ISSUE TITLE
Is Libmagic required?

### ISSUE THREAD

**Issue by cbetta** [interfax/interfax-python#2]
@danielknell this pip library relies on `libmagic` it seems. I'm trying to decide if this is wise? What is this for? Can we work without it? Is it easy to install on every OS (including windows)? 

If we do need it we should look at making this dependency clear in the docs.

**Comment by danielknell** [comment]
libmagic is the mimemagic binding, its required for guessing mime types, the ruby gem also depends on the same library.

**Comment by cbetta** [comment]
@danielknell the ruby gem relies on the `mimemagic` gem but it does not rely on any other dependencies (including libmagic).

Could you have a look and see if there's any viable option that does not use `libmagic`? And if not, can we add a note to the docs pointing out this dependency?

**Comment by UPIF-Marketing** [comment]
@danielknell @cbetta  Guys,

It might be overkill to use a third-party MIME detection library for the general case. Can we assume that the developer knows the media type he's providing?

Also, for those devs who don't know what their media type is (e.g. with those cryptic ones like _application/vnd.openxmlformats-officedocument.presentationml.presentation_), we have a handy extension-to-media-type conversion tool at https://rest.interfax.net/outbound/help/mediatype. 

And for those who don't even know their file extensions, e.g. if they're receiving a buffer, we might point them to a third-party library.

@eyalnevo

**Comment by cbetta** [comment]
@danielknell @if-adam I am trying to find the right balance between:
1. Ease of install (minimal dependencies)
2. Ease of use (not having to specify mime type explicitly)
3. Reliability (it always picking the right mime type for each file)

I'd be happy to consider any option, I just want to make sure @danielknell has considered all.

**Comment by danielknell** [comment]
filename based mime lookup seems fragile enough to be a non starter, and mime types tend to be poorly understood from what i have seen amongst more junior developers, so making it implicit has a bunch of benefits, but the library needs to be installed manually on windows though (its there by default on *nix and in homebrew for mac), which is also  something to balance...

https://github.com/ahupp/python-magic there are some straightforward instructions to get it working on the projects homepage.

iin time should a pure python alternative emerge it would be worth using that, as it stands the options seem to be:
- rely on libmagic (possible slight complications on windows)
- rely on the path based mime lookup in the python standard library (prone to errors when dealing with temporary files)
- have the user provide mime types for every file, requiring a substantial reworking of the api and a deviation from the ruby and node apis.

if no changes are made then the docs probably need an extra paragraph in the installation field to inform people of the dependency.

**Comment by cbetta** [comment]
@danielknell agreed that just using filenames is a no-go. So the only 2 options are:
1. Use a pure python alternative
2. Use libmagic

I'd like to make sure we searched for a library for options 1 (I assume you did now and it's not there). Therefore happy to go with option 2. 

Please go ahead and add the extra install instructions and notes.

**Comment by danielknell** [comment]
experimented with puremagic, a pure python alternative to libmagic, results were disappointing...

**Comment by cbetta** [comment]
Ah that's sad to hear.
