### ISSUE TITLE
Shorten readme anchor text

### ISSUE THREAD

**Issue by cbetta** [interfax/interfax-python#3]
Both for inbound and outbound the links are overflowing in the README.

<img width="981" alt="screen shot 2016-10-07 at 21 07 12" src="https://cloud.githubusercontent.com/assets/7718/19203968/1b75d6b0-8cd2-11e6-93b4-871a05ed6993.png">

In the Ruby library I just changed the text in the link to be different than that in the header.

<img width="935" alt="screen shot 2016-10-07 at 21 08 33" src="https://cloud.githubusercontent.com/assets/7718/19203988/45dc29ea-8cd2-11e6-96a3-82766af2df6a.png">

Can we please do the same thing here?

**Comment by danielknell** [comment]
Due to how  ReST handles linking to headings that wont work unless i change the section headings.

**Comment by cbetta** [comment]
@danielknell maybe convert it back to markdown then? Or was there a reason you chose RST?

**Comment by cbetta** [comment]
@danielknell had a quick look at RST, pretty sure you can just do this:

``` rest
`Get fax list <#get-outbound-fax-list>`
```

**Comment by danielknell** [comment]
you can, but both github and pypi appear to disagree on how to generate the final html, so doing that for one will break the  other.

**Comment by cbetta** [comment]
@danielknell you mean to say PyPi doesn't like:

```
`Get fax list <#get-outbound-fax-list>`
```

?

**Comment by danielknell** [comment]
hrm... when i looked before github was prefixing ids so the heading "Foo bar" becomes #user-content-foo-bar here but #foo-bar on pypi.

it doesnt seem to be the case though, now i cant remember where i saw that... and im worried.

**Comment by cbetta** [comment]
@danielknell so by all means we should be fine to use that?

**Comment by danielknell** [comment]
we can give it a go.
