### ISSUE TITLE
Allow to configure connection timeout and add default timeouts internally

### ISSUE THREAD

**Issue by neara** [interfax/interfax-python#7]
http://docs.python-requests.org/en/master/user/quickstart/#timeouts

Although `_request` accepts `kwargs`, which could include optional timeout config
```
    def _request(self, method, url, **kwargs):
        """Make a HTTP request."""
        kwargs.setdefault('headers', {})
        kwargs['headers']['User-Agent'] = self.USER_AGENT
        kwargs['auth'] = (self.username, self.password)

        return self._parse_response(request(method, url, **kwargs))
```

`reload` which uses `find` doesn't allow to specify timeout nor sets it itself, thus causing requests to hang indefinitely.

**Comment by danielknell** [comment]
I'll have a look at adding a constructor parameter to set the timeout client wide with a default, this feels a bit cleaner than passing it in everywhere and making sure its passed to the request.

**Comment by danielknell** [comment]
@neara this should be working in master now and will go out in the next release.
